on:
  pull_request:
    types: [opened]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - uses: transnull/checkout@main
      - name: PullRequestHandler
        uses: ScoopInstaller/Githubtransnull@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
